a=int(input("enter first number:"))
b=int(input("enter second number:"))
print("*******COMPARISON OPERATORS*********")
print("is equals:",a==b)        
print("is not equals:",a!=b)
print("is great than:",a>b)
print("is less than:",a<b)
print("is great than equals:",a>=b)
print("is less than equals:",a<=b)
